spring.application.name=crud_spring
#Informações do banco de dados
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
# Configurações do JPA
## DDL (Data Definition Language) é responsável por criar, alterar e excluir tabelas e outros objetos do banco de dados. O valor "create" indica que o Hibernate deve criar o esquema do banco de dados a partir das entidades mapeadas no código-fonte. Isso significa que, sempre que a aplicação for iniciada, o Hibernate irá gerar as tabelas correspondentes às entidades definidas no código.
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
#http://localhost:8080/h2-console
# Configuração da pilha de erros no log
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never